// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tct_Magazina;

namespace tct_Magazina.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190930182706_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("tct_Magazina.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("email");

                    b.HasKey("ManagerId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("tct_Magazina.Models.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("SectorId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Sectors");
                });

            modelBuilder.Entity("tct_Magazina.Models.Warehouse", b =>
                {
                    b.Property<int>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Area");

                    b.Property<string>("Location");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("NoOfWorkers");

                    b.Property<int?>("SectorId");

                    b.HasKey("WarehouseId");

                    b.HasIndex("SectorId");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("tct_Magazina.Models.Sector", b =>
                {
                    b.HasOne("tct_Magazina.Models.Manager")
                        .WithMany("Sectors")
                        .HasForeignKey("ManagerId");
                });

            modelBuilder.Entity("tct_Magazina.Models.Warehouse", b =>
                {
                    b.HasOne("tct_Magazina.Models.Sector")
                        .WithMany("Warehouses")
                        .HasForeignKey("SectorId");
                });
#pragma warning restore 612, 618
        }
    }
}
